# Generated by Django 4.2 on 2025-01-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_aceess',
            new_name='last_access',
        ),
    ]
